## Pandas Basics

In [5]:
import pandas as pd
import numpy as np

<img src="/Users/abhishek/Machine-Learning/Numpy/images/numpy_5.jpeg" width="500">

#### Create a numpy array of each column and then convert that data into Panda Dataframe

In [13]:
#creating seperate arrays for each column

order_id = np.arange(1,100001,1)
product_id = np.random.randint(1,101,100000)
customer_id = np.random.randint(1,10001,100000)
product_price = np.random.randint(5,501,100000)
discount = np.random.randint(0,31,100000)
qty = np.random.randint(1,6,100000)


modified_discount = discount/100
revenue = qty*product_price * 1-modified_discount

In [14]:
#creating data frame from numpy arrays 

df = pd.DataFrame({"order_id":order_id,"product_id":product_id,"customer_id":customer_id,"product_price":product_price,"discount":discount,"qty":qty,"revenue":revenue})

In [15]:
# view the first 5 entries of dataset
df.head(5)

   order_id  product_id  customer_id  product_price  discount  qty  revenue
0         1          96         7564            139        30    2   277.70
1         2           8         1268             28        30    3    83.70
2         3          62          392             85        30    3   254.70
3         4          25         9256            426        19    4  1703.81
4         5          72         1477            446        26    3  1337.74

In [16]:
#basic operations 
df.count()
a= df.product_price.mean()
int(a)
df.min()
df.max()

order_id         100000.0
product_id          100.0
customer_id       10000.0
product_price       500.0
discount             30.0
qty                   5.0
revenue            2500.0
dtype: float64

In [17]:
df.describe()

,order_id,product_id,customer_id,product_price,discount,qty,revenue
count,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000
mean,50000.500000,50.474190,4997.089160,252.92335,15.030420,2.998010,758.253596
std,28867.657797,28.844513,2880.883529,143.59796,8.942185,1.417465,595.789866
min,1.000000,1.000000,1.000000,5.00000,0.000000,1.000000,4.710000
25%,25000.750000,26.000000,2505.000000,129.00000,7.000000,2.000000,279.857500
50%,50000.500000,50.000000,4999.000000,253.00000,15.000000,3.000000,593.960000
75%,75000.250000,75.000000,7487.000000,378.00000,23.000000,4.000000,1124.940000
max,100000.000000,100.000000,10000.000000,500.00000,30.000000,5.000000,2500.000000

<img src="/Users/abhishek/Machine-Learning/Numpy/images/pandas_1.jpeg" width="500">

In [26]:
# Display every order where revenue is greater than 500 Euros

revenue_greater_500 = df[df["revenue"]>500]
revenue_greater_500

,order_id,product_id,customer_id,product_price,discount,qty,revenue
3,4,25,9256,426,19,4,1703.81
4,5,72,1477,446,26,3,1337.74
5,6,40,6627,459,25,3,1376.75
6,7,48,6078,382,0,4,1528.00
7,8,34,9003,367,25,2,733.75
...,...,...,...,...,...,...,...
99992,99993,37,3784,214,27,5,1069.73
99995,99996,89,8205,204,23,4,815.77
99996,99997,53,5920,143,29,5,714.71
99998,99999,57,3451,477,13,3,1430.87
99999,100000,96,7065,326,22,3,977.78

In [29]:
#Find all orders where revenue > €500 AND discount >= 20%.

revenue_greater_500_discount_less_20 = df[(df["revenue"]>500) & (df["discount"]<=20)]
revenue_greater_500_discount_less_20

,order_id,product_id,customer_id,product_price,discount,qty,revenue
3,4,25,9256,426,19,4,1703.81
6,7,48,6078,382,0,4,1528.00
12,13,63,3393,223,20,5,1114.80
13,14,13,4530,288,18,3,863.82
17,18,46,18,339,12,4,1355.88
...,...,...,...,...,...,...,...
99984,99985,67,3953,261,19,3,782.81
99989,99990,85,7803,272,12,4,1087.88
99990,99991,26,8078,366,7,5,1829.93
99991,99992,6,2114,286,3,2,571.97
99998,99999,57,3451,477,13,3,1430.87

In [31]:
#Give me the 10 highest-revenue orders.

sorted_data = df.sort_values("revenue",ascending=False)
sorted_data.head(10)

,order_id,product_id,customer_id,product_price,discount,qty,revenue
81928,81929,33,9735,500,0,5,2500.00
37722,37723,58,6061,500,0,5,2500.00
49910,49911,70,4850,500,1,5,2499.99
45705,45706,17,3403,500,2,5,2499.98
30765,30766,99,9981,500,2,5,2499.98
40000,40001,28,2087,500,3,5,2499.97
88147,88148,72,8473,500,4,5,2499.96
39391,39392,5,8808,500,5,5,2499.95
59153,59154,13,7763,500,7,5,2499.93
6902,6903,3,8882,500,7,5,2499.93

In [32]:
customer_revenue = df.groupby("customer_id")["revenue"].sum()
#top 10 customer reveneue
customer_revenue=pd.DataFrame(customer_revenue)
customer_revenue.sort_values("revenue",ascending=False)
customer_revenue.head(10)

              revenue
customer_id
1            10565.83
2             5127.36
3             4994.43
4             5651.86
5             6596.34
6             3693.92
7             5292.87
8             3631.32
9            12113.02
10           11553.14

In [34]:
# For each customer, tell me: total revenue,average order revenue,number of orders
x = df.groupby("customer_id")["revenue"].agg(['sum','mean','count'])
x

                  sum         mean  count
customer_id
1            10565.83  1173.981111      9
2             5127.36   732.480000      7
3             4994.43   624.303750      8
4             5651.86   627.984444      9
5             6596.34   659.634000     10
...               ...          ...    ...
9996         13590.58   566.274167     24
9997          2529.53   843.176667      3
9998          6555.21   819.401250      8
9999          7424.36   571.104615     13
10000         6441.56   715.728889      9

[9998 rows x 3 columns]

In [35]:
#For each product, how many units were sold and how much revenue did it generate?

sold_units = df.groupby("product_id")["qty"].sum()
revenue_t = sold_units*df.product_price
product_stats = df.groupby("product_id").agg({
    "qty": "sum",
    "revenue": "sum"
})

In [36]:
top_10_p= product_stats.sort_values("revenue",ascending=False).head(10)

In [37]:
#Give me the order_id, customer_id, revenue, and discount for the 20 highest-revenue orders.
top20 = product_stats.sort_values("revenue",ascending=False).head(20)
top20

             qty    revenue
product_id
75          3212  828561.25
97          3163  826141.78
68          3178  813733.29
7           3171  806084.85
80          3091  804057.36
47          3147  803011.63
55          3118  802373.14
4           3051  801733.05
42          3141  796146.39
67          3082  794251.87
63          3113  791350.97
19          3049  791217.12
92          3090  790978.86
31          3052  790968.78
73          3043  790267.82
18          3088  787144.77
8           3081  785962.99
36          3018  785772.65
22          3110  783938.86
13          3003  783791.12