# Dataset Requirements

Create a dataset containing **1,00,000 orders** with the following columns:

| Column | Description |
|---|---|
| `order_id` | Unique ID for each order |
| `customer_id` | ID of the customer |
| `product_id` | ID of the product |
| `product_price` | Price of the product in euros |
| `qty` | Quantity ordered |
| `discount` | Discount percentage |

## Assumptions

- **Total Orders:** 1,00,000
- **Total Customers:** 10,000
- **Total Products:** 100
- **Quantity (`qty`):** 1–5
- **Product Price (`product_price`):** €5–€500
- **Discount (`discount`):** 0%–30%

In [3]:
import numpy as np

In [4]:
order_id = np.arange(1,100001,1)
product_id = np.random.randint(1,101,100000)
customer_id = np.random.randint(1,10001,100000)
product_price = np.random.randint(5,501,100000)
discount = np.random.randint(0,31,100000)
qty = np.random.randint(1,6,100000)

In [5]:
print(order_id)
print("----------")
print(product_id)
print("----------")
print(customer_id)
print("----------")
print(product_price)

print("----------")
print(qty)
print("----------")

print(discount)

[     1      2      3 ...  99998  99999 100000]
----------
[ 44  14  62 ...  95 100  93]
----------
[3694 1342 3581 ...  236  168 6595]
----------
[433 466 141 ... 166 400 499]
----------
[4 5 1 ... 1 4 4]
----------
[15  4 11 ...  8 27 11]

#Revenue calculation 

Revenue=Quantity×Price×(1−Discount/100)

In [6]:
modified_discount = discount/100
revenue = qty*product_price * 1-modified_discount

In [7]:
revenue

array([1731.85, 2329.96,  140.89, ...,  165.92, 1599.73, 1995.89],
      shape=(100000,))

In [8]:
total_revenue = revenue.sum()
print("Total Revenue :",int(total_revenue))

average_order_revenue = int(total_revenue)/100000
print("Average Revenue : ",int(average_order_revenue))

Total Revenue : 75725320
Average Revenue :  757

In [14]:
# all transcation where revenue after discount was more than 500 euros

revenue_more_500 = revenue[revenue>500]
revenue_more_500
total_such_order = revenue_more_500.size
total_such_order

54861

In [15]:
# which order generated revenue more than 500

mask1 = revenue>500
print(order_id[mask1])

[     1      2      4 ...  99996  99999 100000]

In [20]:
#Find orders where revenue was greater than €500 AND the discount was less than 10%.
mask2 = (revenue>500) & (discount<10)
print(revenue[mask2])

[2329.96  935.92  967.96 ... 1404.91 1989.91  854.91]

In [28]:
revenue.argmax()

np.int64(16897)

In [29]:
#What are the 10 highest-revenue orders, and what are their order IDs?

mask3 = revenue.argsort()
inds = mask3[-10:]
order_id[inds]

array([39690,  7867, 74194,  5074, 17986, 42682,  1087, 79244, 16898,
       41841])

In [34]:
#Which 10 customers generated the most revenue?

all_customer_revenue = np.bincount(customer_id,weights=revenue)
all_customer_revenue_sorted_map = np.argsort(all_customer_revenue)
top_10_customer =all_customer_revenue_sorted_map[-10:]
top_10_customer

array([5460,  609,  137, 8574,  571,  274,  298, 5539, 7881, 7680])

In [35]:
threshold = np.percentile(revenue, 90)
mask4 = revenue > threshold
order_id[mask4]

array([     1,      2,      8, ...,  99986,  99993, 100000],
      shape=(10000,))

In [36]:
threshold = np.percentile(revenue, 90)
mask5 = (revenue > threshold) & (discount>20)
order_id[mask5]

array([   13,    33,    60, ..., 99954, 99986, 99993], shape=(3184,))

In [41]:
top_10_orders = order_id[mask4]
top_10_orders.size
revenue_top_10 = top_10_orders.sum()
average_top_revenue = revenue_top_10/top_10_orders.size
top_10_qty = top_10_orders.size

## Pandas

In [43]:
import pandas as pd

In [44]:
df = pd.DataFrame({
     "order_id": order_id,
    "customer_id": customer_id,
    "product_id": product_id,
    "product_price": product_price,
    "discount": discount,
    "qty": qty,
    "revenue": revenue
})

In [45]:
df

,order_id,customer_id,product_id,product_price,discount,qty,revenue
0,1,3694,44,433,15,4,1731.85
1,2,1342,14,466,4,5,2329.96
2,3,3581,62,141,11,1,140.89
3,4,1445,95,234,8,4,935.92
4,5,6022,54,242,4,4,967.96
...,...,...,...,...,...,...,...
99995,99996,6920,73,173,22,3,518.78
99996,99997,3450,38,387,1,1,386.99
99997,99998,236,95,166,8,1,165.92
99998,99999,168,100,400,27,4,1599.73
99999,100000,6595,93,499,11,4,1995.89

In [46]:
df.shape

(100000, 7)

In [47]:
df.head(5)

   order_id  customer_id  product_id  product_price  discount  qty  revenue
0         1         3694          44            433        15    4  1731.85
1         2         1342          14            466         4    5  2329.96
2         3         3581          62            141        11    1   140.89
3         4         1445          95            234         8    4   935.92
4         5         6022          54            242         4    4   967.96

In [59]:
df.count()
a= df.product_price.mean()
int(a)
df.min()
df.max()

order_id         100000.0
customer_id       10000.0
product_id          100.0
product_price       500.0
discount             30.0
qty                   5.0
revenue            2500.0
dtype: float64

In [60]:
df.describe()

,order_id,customer_id,product_id,product_price,discount,qty,revenue
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,4997.412010,50.375670,251.880890,15.040600,3.005850,757.253204
std,28867.657797,2886.697506,28.857158,143.406659,8.952124,1.412394,594.180131
min,1.000000,1.000000,1.000000,5.000000,0.000000,1.000000,4.700000
25%,25000.750000,2493.750000,25.000000,128.000000,7.000000,2.000000,281.727500
50%,50000.500000,5002.500000,50.000000,252.000000,15.000000,3.000000,593.965000
75%,75000.250000,7490.000000,75.000000,376.000000,23.000000,4.000000,1124.705000
max,100000.000000,10000.000000,100.000000,500.000000,30.000000,5.000000,2500.000000

In [61]:
#Show me every order where revenue is greater than €500.
df[revenue>500]

,order_id,customer_id,product_id,product_price,discount,qty,revenue
0,1,3694,44,433,15,4,1731.85
1,2,1342,14,466,4,5,2329.96
3,4,1445,95,234,8,4,935.92
4,5,6022,54,242,4,4,967.96
6,7,2721,73,130,16,4,519.84
...,...,...,...,...,...,...,...
99992,99993,8259,45,441,23,4,1763.77
99994,99995,7434,77,285,9,3,854.91
99995,99996,6920,73,173,22,3,518.78
99998,99999,168,100,400,27,4,1599.73
99999,100000,6595,93,499,11,4,1995.89

In [ ]:
#Find all orders where revenue > €500 AND discount >= 20%.

high_discount_orders = df[
    (df["revenue"] > 500) &
    (df["discount"] >= 20)
]

In [64]:
#Give me the 10 highest-revenue orders.

sorted_data = df.sort_values("revenue",ascending=False)
sorted_data.head(10)

,order_id,customer_id,product_id,product_price,discount,qty,revenue
16897,16898,6420,3,500,0,5,2500.00
41840,41841,8976,20,500,0,5,2500.00
79243,79244,4751,57,500,2,5,2499.98
1086,1087,6584,30,500,4,5,2499.96
17985,17986,7168,70,500,5,5,2499.95
42681,42682,6774,86,500,5,5,2499.95
7866,7867,251,48,500,6,5,2499.94
74193,74194,8129,2,500,6,5,2499.94
39689,39690,78,88,500,6,5,2499.94
5073,5074,8578,7,500,6,5,2499.94

In [ ]:
customer_revenue = df.groupby("customer_id")["revenue"].sum()
#top 10 customer reveneue
customer_revenue=pd.DataFrame(customer_revenue)
customer_revenue.sort_values("revenue",ascending=False)
customer_revenue.head(10)

              revenue
customer_id
1             6629.70
2             5345.03
3             8629.90
4             7139.80
5             8661.71
6            13308.74
7             5712.13
8            10088.11
9             6363.57
10            7626.59

In [90]:
"""For each customer, tell me:

total revenue
average order revenue
number of orders"""

x = df.groupby("customer_id")["revenue"].agg(['sum','mean','count'])

In [91]:
x

                 sum        mean  count
customer_id
1            6629.70  662.970000     10
2            5345.03  534.503000     10
3            8629.90  784.536364     11
4            7139.80  892.475000      8
5            8661.71  787.428182     11
...              ...         ...    ...
9996         4824.98  482.498000     10
9997         7947.57  883.063333      9
9998         3138.02  523.003333      6
9999         5854.46  836.351429      7
10000        3350.11  558.351667      6

[10000 rows x 3 columns]

In [97]:
#For each product, how many units were sold and how much revenue did it generate?

sold_units = df.groupby("product_id")["qty"].sum()
revenue_t = sold_units*df.product_price
product_stats = df.groupby("product_id").agg({
    "qty": "sum",
    "revenue": "sum"
})

In [ ]:
top_10_p= product_stats.sort_values("revenue",ascending=False).head(10)

             qty    revenue
product_id
82          3175  818485.10
57          3080  816195.92
6           3170  815693.19
3           3226  811788.76
73          3192  811250.69
...          ...        ...
12          3011  708979.03
80          2741  700002.66
59          2791  690917.45
29          2803  690268.83
97          2823  682720.75

[100 rows x 2 columns]